export const allLoans = [
	{
		id: '1',
		user: 'Momochi@gmail.com',
		createdOn: 'March 24th, 2018',
		status: 'pending',
		repaid: false,
		tenor: 2,
		amount: 50000,
		paymentInstallment: 2.5,
		balance: 15000,
		interest: 0.20,
	},
	{
		id: '2',
		user: 'chid@gmail.com',
		createdOn: 'March 24th, 2018',
		status: 'pending',
		repaid: true,
		tenor: 2,
		amount: 50000,
		paymentInstallment: 2.5,
		balance: 0,
		interest: 0.20,
	},
]
